# Site settings
title: AR-GE TEKNOLOJİ VE İNOVASYON KULÜBÜ
shortTitle: ATİK
email: ar-getit@outlook.com
url: https://www.gtuatik.com
description: "/düzenleniyor/"



menu:
- {home: Ana Sayfa, link: '/'}
- {events: Etkinlikler, link: '/events'}
- {about-us: Hakkımızda, link: '/about-us'}
- {contact-us: İletişim, link: '/contact-us'}


# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#2bf0e3'

# Footer settings
footer: gtuatik.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/gtuatik/
  - title: linkedin
    url: https://www.linkedin.com/company/

# Build settings
permalink: /:basename:output_ext
